### ISSUE TITLE
doesn't work in mode 1-3

### ISSUE THREAD

**Issue by guxd** [jacoxu/encoder_decoder#1]

**Comment by dapeng2018** [comment]
what is the version of Keras you used?

**Comment by guxd** [comment]
I use the latest keras. I guess it could be due to incorrect installation of the seq2seq library.  I am fixing..

**Comment by dapeng2018** [comment]
As I know, the seq2seq library cannot work with keras 1.0, it can work with keras 0.3.3, maybe you should install keras with version of 0.3.3, and the link is https://testpypi.python.org/pypi/Keras/0.3.3

**Comment by jacoxu** [comment]
YES, The suggested version of Keras is 0.3.3, for some old style functions are called in seq2seq.

**Comment by guxd** [comment]
OK, fixed. Thanks!

**Comment by jacoxu** [comment]
okay
