### ISSUE TITLE
run encoder_decoder.py error

### ISSUE THREAD

**Issue by cc946079647** [jacoxu/encoder_decoder#2]
when I run

> python encoder_decoder.py
> I got this error:
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "encoder_decoder.py", line 9, in <module>
>     from seq2seq.layers.decoders import LSTMDecoder, LSTMDecoder2, AttentionDecoder
> ImportError: No module named layers.decoders
> It seems something about seq2seq,but I have installed it.
> pip list | grep seq2seq
> seq2seq (0.1.0)
> Does anyone has encountered this problem？

**Comment by jacoxu** [comment]
Thanks for your reminding. I noted that Fariz Rahman has changed the seq2seq package. In order to avoid the version mismatch of Seq2seq and Keras. I uploaded these packages into this repository.
